apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data: 
  SERVER_NAME: <rds server name in base 64 encoded format>
##kubectl get secrets/app-secrets --template={{.data.MONGO_URL}} | base64 -d
  DB_USERNAME: <rds mysql user name in base64 encoded format>
  DB_PASSWORD: <rds mysql password in base64 encoded format>
